### ISSUE TITLE
方便的话，可以上传一下其他学科的资料吗？

### ISSUE THREAD

**Issue by plusmultiply0** [Ricky-Chu/lib-cs-hhu#9]
比如：
- 马克思原理、毛概之类的

这些课程计算机类专业也需要学习吧，勉强也算是计算机类。

只是提个建议，感谢你们的分享，非常有帮助，谢谢！

**Comment by Ricky-Chu** [comment]
感谢建议！之前考虑过一些非计算机课程的加入，但由于

l  项目是个人维护，平时精力有限，保证更新已实属困难。

l  考虑到公共课的课程资料更新较快且每个老师也有差别，因此当初暂未做考虑。

l  更多的是想分享专业课的知识
上述其实有很多主观因素，考虑到项目毕竟是为所有同学服务的，且即将转接，我会将这个建议告知他的。
在两个星期内，我会上传一些其他学科的资料！拭目以待！


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kim Zhou <notifications@github.com>
发送时间: Friday, August 28, 2020 3:10:51 PM
收件人: Ricky-Chu/lib-cs-hhu <lib-cs-hhu@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Ricky-Chu/lib-cs-hhu] 方便的话，可以上传一下其他学科的资料吗？ (#9)


比如：

  *   马克思原理、毛概之类的

这些课程计算机类专业也需要学习吧，勉强也算是计算机类。

只是提个建议，感谢你们的分享，非常有帮助，谢谢！

―
